# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62eea73df3945cf8c7e34c6a40516ce8aeafe5b769174d2adec09ba90c46c140fd00bfefa07bfe7303a94b09f86ce21589e7d3afc330fd297400d2be6a972f75

test:
  secret_key_base: da9fe55ec9e336943ee2ab4dfa24225878e21d0699405d082a8317f3c3e52295bc26108d4f9ff93431109cd84d7b6126879ffa4713da169ee1745118d5e491ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
